import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import React from "react";
import { UiContextProvider } from "@/store/ui-context";
import { LanguageProvider } from "@/store/language-context";
import HeaderNavMenu from "@/components/NavMenu/HeaderNavMenu";
import Footer from "@/components/Footer/Footer";
import { FavoritesProvider } from "@/store/favorites-context";

const sans = Open_Sans({
  variable: "--font-open_sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Trapezi ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sans.variable}  antialiased`}>
        <UiContextProvider>
          <LanguageProvider>
            <FavoritesProvider>
              <Toaster position="top-center" />
              <HeaderNavMenu />
              {children}
              <Footer />
            </FavoritesProvider>
          </LanguageProvider>
        </UiContextProvider>
      </body>
    </html>
  );
}
